export const jokes = [
    "Why don't skeletons fight each other?<br><br> They don't have the guts.",
    "What do you call fake spaghetti?<br><br> An impasta!",
    "Why did the scarecrow win an award?<br><br> Because he was outstanding in his field!",
    "Why don't some couples go to the gym?<br><br> Because some relationships don't work out.",
    "What do you get when you cross a snowman and a vampire?<br><br> Frostbite.",
    "Why don't scientists trust atoms?<br><br> Because they make up everything!",
    "Why did the math book look sad?<br><br> Because it had too many problems.",
    "Why was the math lecture so long?<br><br> The teacher kept going off on a tangent.",
    "Why did the bicycle fall over?<br><br> It was two-tired!",
    "What do you call cheese that isn't yours?<br><br> Nacho cheese.",
    "Why don't oysters share their pearls?<br><br> Because they're shellfish.",
    "How do you organize a space party?<br><br> You planet!",
    "Why did the tomato turn red?<br><br> Because it saw the salad dressing.",
    "Why did the golfer bring two pairs of pants?<br><br> In case he got a hole in one.",
    "What do you call a dinosaur with an extensive vocabulary?<br><br> A thesaurus.",
    "Why was the broom late?<br><br> It swept in.",
    "Why did the coffee file a police report?<br><br> It got mugged.",
    "Why was the computer cold?<br><br> It left its Windows open.",
    "How do you make a tissue dance?<br><br> You put a little boogie in it.",
    "Why did the music teacher go to jail?<br><br> Because she got caught with a bunch of notes.",
    "What did one plate say to the other plate?<br><br> Lunch is on me.",
    "Why did the belt go to jail?<br><br> Because it held up a pair of pants.",
    "Why can't you give Elsa a balloon?<br><br> Because she will let it go.",
    "Why did the cookie go to the doctor?<br><br> Because it felt crummy.",
    "Why don't eggs tell jokes?<br><br> They might crack up.",
    "How does a penguin build its house?<br><br> Igloos it together.",
    "What do you call a factory that makes good products?<br><br> A satisfactory.",
    "Why did the gym close down?<br><br> It just didn't work out!",
    "What do you call a boomerang that doesn't come back?<br><br> A stick.",
    "What did the janitor say when he jumped out of the closet?<br><br> Supplies!",
    "Why did the golfer bring an extra pair of socks?<br><br> In case he got a hole in one.",
    "Why don't seagulls fly over the bay?<br><br> Because then they'd be bagels.",
    "What do you call a bear with no teeth?<br><br> A gummy bear.",
    "Why don't you play cards in the jungle?<br><br> Because there are too many cheetahs.",
    "What do you call a cow with no legs?<br><br> Ground beef.",
    "What did the grape do when he got stepped on?<br><br> Nothing but let out a little wine!",
    "Why are elevator jokes so good?<br><br> They work on so many levels.",
    "Why was the math book sad?<br><br> It had too many problems.",
    "How does a cucumber become a pickle?<br><br> It goes through a jarring experience.",
    "Why don't cows have any money?<br><br> Because the farmers milk them dry.",
    "Why did the mushroom go to the party alone?<br><br> Because he's a fungi.",
    "Why don't some couples go to the gym?<br><br> Because some relationships don't work out.",
    "Why did the bicycle fall over?<br><br> Because it was two-tired.",
    "What do you call a cow with no legs?<br><br> Ground beef.",
    "Why did the scarecrow win an award?<br><br> Because he was outstanding in his field.",
    "What do you call fake spaghetti?<br><br> An impasta.",
    "Why don't skeletons fight each other?<br><br> They don't have the guts.",
    "Why don't scientists trust atoms?<br><br> Because they make up everything!",
    "Why did the chicken join a band?<br><br> Because it had the drumsticks.",
    "Why don't oysters share their pearls?<br><br> Because they're shellfish.",
    "Why did the golfer bring two pairs of pants?<br><br> In case he got a hole in one.",
    "What do you call a dinosaur with an extensive vocabulary?<br><br> A thesaurus.",
    "Why was the broom late?<br><br> It swept in.",
    "Why did the coffee file a police report?<br><br> It got mugged.",
    "Why was the computer cold?<br><br> It left its Windows open.",
    "How do you make a tissue dance?<br><br> You put a little boogie in it.",
    "Why did the music teacher go to jail?<br><br> Because she got caught with a bunch of notes.",
    "What did one plate say to the other plate?<br><br> Lunch is on me.",
    "Why did the belt go to jail?<br><br> Because it held up a pair of pants.",
    "Why can't you give Elsa a balloon?<br><br> Because she will let it go.",
    "Why did the cookie go to the doctor?<br><br> Because it felt crummy.",
    "Why don't eggs tell jokes?<br><br> They might crack up.",
    "How does a penguin build its house?<br><br> Igloos it together.",
    "What do you call a factory that makes good products?<br><br> A satisfactory.",
    "Why did the gym close down?<br><br> It just didn't work out!",
    "What do you call a boomerang that doesn't come back?<br><br> A stick.",
    "What did the janitor say when he jumped out of the closet?<br><br> Supplies!",
    "Why did the golfer bring an extra pair of socks?<br><br> In case he got a hole in one.",
    "Why don't seagulls fly over the bay?<br><br> Because then they'd be bagels.",
    "What do you call a bear with no teeth?<br><br> A gummy bear.",
    "Why don't you play cards in the jungle?<br><br> Because there are too many cheetahs.",
    "What do you call a cow with no legs?<br><br> Ground beef.",
    "What did the grape do when he got stepped on?<br><br> Nothing but let out a little wine!",
    "Why are elevator jokes so good?<br><br> They work on so many levels.",
    "Why was the math book sad?<br><br> It had too many problems.",
    "How does a cucumber become a pickle?<br><br> It goes through a jarring experience.",
    "Why don't cows have any money?<br><br> Because the farmers milk them dry.",
    "Why did the mushroom go to the party alone?<br><br> Because he's a fungi.",
    "Why don't some couples go to the gym?<br><br> Because some relationships don't work out.",
    "Why did the bicycle fall over?<br><br> Because it was two-tired.",
    "What do you call a cow with no legs?<br><br> Ground beef.",
    "Why did the scarecrow win an award?<br><br> Because he was outstanding in his field.",
    "What do you call fake spaghetti?<br><br> An impasta.",
    "Why don't skeletons fight each other?<br><br> They don't have the guts.",
    "Why don't scientists trust atoms?<br><br> Because they make up everything!",
    "Why did the chicken join a band?<br><br> Because it had the drumsticks.",
    "Why don't oysters share their pearls?<br><br> Because they're shellfish.",
    "Why did the golfer bring two pairs of pants?<br><br> In case he got a hole in one.",
    "What do you call a dinosaur with an extensive vocabulary?<br><br> A thesaurus."
  ];
  